#include <chrono>
#include <functional>
#include <iomanip>
#include <iostream>
#include <map>
#include <memory>
#include <variant>

#include <ql/config.hpp>

#include <ql/cashflows/iborcoupon.hpp>
#include <ql/handle.hpp>
#include <ql/indexes/ibor/estr.hpp>
#include <ql/instruments/makeois.hpp>
#include <ql/math/interpolations/convexmonotoneinterpolation.hpp>
#include <ql/pricingengines/swap/discountingswapengine.hpp>
#include <ql/quotes/simplequote.hpp>
#include <ql/termstructures/yield/oisratehelper.hpp>
#include <ql/termstructures/yield/piecewiseyieldcurve.hpp>
#include <ql/time/daycounters/actual360.hpp>

using std::bad_variant_access;
using std::cout;
using std::defaultfloat;
using std::fixed;
using std::function;
using std::get;
using std::holds_alternative;
using std::make_shared;
using std::map;
using std::max;
using std::min;
using std::pair;
using std::setprecision;
using std::shared_ptr;
using std::variant;
using std::vector;
using std::chrono::duration_cast;
using std::chrono::nanoseconds;
using std::chrono::steady_clock;

using QuantLib::Actual360;
using QuantLib::ConvexMonotone;
using QuantLib::Date;
using QuantLib::DateGeneration;
using QuantLib::DiscountingSwapEngine;
using QuantLib::Estr;
using QuantLib::ForwardRate;
using QuantLib::Frequency;
using QuantLib::Handle;
using QuantLib::IborCoupon;
using QuantLib::IndexManager;
using QuantLib::MakeOIS;
using QuantLib::Month;
using QuantLib::OISRateHelper;
using QuantLib::OvernightIndex;
using QuantLib::OvernightIndexedSwap;
using QuantLib::Period;
using QuantLib::PiecewiseYieldCurve;
using QuantLib::Quote;
using QuantLib::RateHelper;
using QuantLib::RelinkableHandle;
using QuantLib::Settings;
using QuantLib::SimpleQuote;
using QuantLib::Swap;
using QuantLib::TimeSeries;
using QuantLib::TimeUnit;
using QuantLib::YieldTermStructure;

using AbsoluteOrRelativeDate = variant<Date, Period>;

class DiscountingCurveDemo {
  static const Date today;
  static const map<Date, double> fixings;
  static const map<Period, double> swapRates;
  static const vector<pair<AbsoluteOrRelativeDate, AbsoluteOrRelativeDate>> calcSwapTenors;

  template <typename T>
  static T dispatch(const AbsoluteOrRelativeDate& date,
                    const function<T(Date)>& dateGetter,
                    const function<T(Period)>& periodGetter) {
    if (holds_alternative<Date>(date)) {
      return dateGetter(get<Date>(date));
    } else if (holds_alternative<Period>(date)) {
      return periodGetter(get<Period>(date));
    } else {
      throw bad_variant_access();
    }
  }

 public:
  static void main() {
    // should be selected on at QuantLib compile time
    QL_ASSERT(!IborCoupon::Settings::instance().usingAtParCoupons(),
              "should use indexed coupons, but using at-par coupons");

    Settings::instance().evaluationDate() = today;

    RelinkableHandle<YieldTermStructure> curveHandle;
    shared_ptr<OvernightIndex> index = make_shared<Estr>(curveHandle);
    int settlementDays = 2;

    IndexManager& indexManager = IndexManager::instance();

    TimeSeries<double> history = indexManager.getHistory(index->name());
    for (const pair<const Date, double>& fixing : fixings) {
      history[fixing.first] = fixing.second;
    }

    indexManager.setHistory(index->name(), history);

    vector<shared_ptr<SimpleQuote>> swapQuotes;
    vector<shared_ptr<RateHelper>> helpers;
    for (const pair<const Period, double>& swapRate : swapRates) {
      shared_ptr<SimpleQuote> quote = make_shared<SimpleQuote>();
      swapQuotes.push_back(quote);

      helpers.push_back(make_shared<OISRateHelper>(settlementDays,
                                                   swapRate.first,
                                                   Handle<Quote>(quote),
                                                   index,
                                                   Handle<YieldTermStructure>(), // QuantLib default
                                                   true));
    }

    shared_ptr<PiecewiseYieldCurve<ForwardRate, ConvexMonotone>> curve =
        make_shared<PiecewiseYieldCurve<ForwardRate, ConvexMonotone>>(today, helpers, index->dayCounter());
    curve->enableExtrapolation();
    curveHandle.linkTo(curve);

    shared_ptr<DiscountingSwapEngine> swapEngine = make_shared<DiscountingSwapEngine>(curveHandle);

    vector<shared_ptr<OvernightIndexedSwap>> swapInstruments;
    for (const pair<AbsoluteOrRelativeDate, AbsoluteOrRelativeDate>& calcSwapTenor : calcSwapTenors) {
      Period forward = dispatch<Period>(
          calcSwapTenor.first,                  //
          [&](Date start) { return Period(); }, //
          [&](Period forward) { return forward; });

      Date effectiveDate = dispatch<Date>(
          calcSwapTenor.first,               //
          [&](Date start) { return start; }, //
          [&](Period forward) { return Date(); });

      swapInstruments.push_back(dispatch<MakeOIS>(
                                    calcSwapTenor.second,
                                    [&](Date end) {
                                      return MakeOIS(Period(), //
                                                     index,    //
                                                     0,
                                                     forward)
                                          .withSettlementDays(settlementDays)
                                          .withTerminationDate(end);
                                    },
                                    [&](Period tenor) {
                                      return MakeOIS(tenor, //
                                                     index, //
                                                     0,
                                                     forward)
                                          .withSettlementDays(settlementDays);
                                    })
                                    .withEffectiveDate(effectiveDate)
                                    .withType(Swap::Payer)
                                    .withNominal(1e6)
                                    .withRule(DateGeneration::Rule::Backward)
                                    .withPaymentFrequency(Frequency::Annual)
                                    .withFixedLegDayCount(Actual360())
                                    .withTelescopicValueDates(true)
                                    .withPricingEngine(swapEngine));
    }

    cout << "iteration"
         << ","
         << "minSwapRate"
         << ","
         << "maxSwapRate"
         << ","
         << "elapsed" << '\n';

    enum class IterationType { WARMUP, MEASUREMENT };

    for (IterationType iterationType = IterationType::WARMUP; //
         iterationType <= IterationType::MEASUREMENT;         //
         iterationType = (IterationType) ((int) iterationType + 1)) {
      for (int iteration = 1; iteration <= 100; ++iteration) {
        map<const Period, double>::const_iterator swapRatesIt;
        vector<shared_ptr<SimpleQuote>>::iterator swapQuotesIt;
        for (swapRatesIt = swapRates.cbegin(), swapQuotesIt = swapQuotes.begin();
             swapRatesIt != swapRates.cend() && swapQuotesIt != swapQuotes.end();
             swapRatesIt++, swapQuotesIt++) {
          (*swapQuotesIt)->setValue(0);
          (*swapQuotesIt)->setValue(swapRatesIt->second);
        }

        steady_clock::time_point start = steady_clock::now();

        vector<double> calcSwapRates;
        calcSwapRates.reserve(swapInstruments.size());
        for (const shared_ptr<OvernightIndexedSwap>& swapInstrument : swapInstruments) {
          calcSwapRates.push_back(swapInstrument->fairRate());
        }

        steady_clock::time_point end = steady_clock::now();

        if (iterationType == IterationType::MEASUREMENT) {
          // make the output depend on the results so they definitely don't get optimised away
          double minSwapRate = 1;
          double maxSwapRate = -1;
          for (double swapRate : calcSwapRates) {
            minSwapRate = min(minSwapRate, swapRate);
            maxSwapRate = max(maxSwapRate, swapRate);
          }

          cout << iteration << ","                                                           //
               << fixed << setprecision(6)                                                   //
               << minSwapRate << ","                                                         //
               << maxSwapRate << ","                                                         //
               << std::chrono::duration_cast<nanoseconds>(end - start).count() / 1e6 << '\n' //
               << defaultfloat;
        }
      }
    }
  }
};

const Date DiscountingCurveDemo::today = Date(25, Month::April, 2024);

const map<Date, double> DiscountingCurveDemo::fixings =
    {{Date(24, Month::April, 2023), 0.02905},     {Date(25, Month::April, 2023), 0.02901},
     {Date(26, Month::April, 2023), 0.02900},     {Date(27, Month::April, 2023), 0.02900},
     {Date(28, Month::April, 2023), 0.02894},     {Date(2, Month::May, 2023), 0.02896},
     {Date(3, Month::May, 2023), 0.02896},        {Date(4, Month::May, 2023), 0.02897},
     {Date(5, Month::May, 2023), 0.02898},        {Date(8, Month::May, 2023), 0.02892},
     {Date(9, Month::May, 2023), 0.02894},        {Date(10, Month::May, 2023), 0.03145},
     {Date(11, Month::May, 2023), 0.03145},       {Date(12, Month::May, 2023), 0.03148},
     {Date(15, Month::May, 2023), 0.03145},       {Date(16, Month::May, 2023), 0.03147},
     {Date(17, Month::May, 2023), 0.03151},       {Date(18, Month::May, 2023), 0.03153},
     {Date(19, Month::May, 2023), 0.03151},       {Date(22, Month::May, 2023), 0.03150},
     {Date(23, Month::May, 2023), 0.03157},       {Date(24, Month::May, 2023), 0.03148},
     {Date(25, Month::May, 2023), 0.03148},       {Date(26, Month::May, 2023), 0.03152},
     {Date(29, Month::May, 2023), 0.03147},       {Date(30, Month::May, 2023), 0.03148},
     {Date(31, Month::May, 2023), 0.03144},       {Date(1, Month::June, 2023), 0.03147},
     {Date(2, Month::June, 2023), 0.03148},       {Date(5, Month::June, 2023), 0.03148},
     {Date(6, Month::June, 2023), 0.03145},       {Date(7, Month::June, 2023), 0.03144},
     {Date(8, Month::June, 2023), 0.03146},       {Date(9, Month::June, 2023), 0.03147},
     {Date(12, Month::June, 2023), 0.03147},      {Date(13, Month::June, 2023), 0.03147},
     {Date(14, Month::June, 2023), 0.03150},      {Date(15, Month::June, 2023), 0.03147},
     {Date(16, Month::June, 2023), 0.03144},      {Date(19, Month::June, 2023), 0.03144},
     {Date(20, Month::June, 2023), 0.03144},      {Date(21, Month::June, 2023), 0.03395},
     {Date(22, Month::June, 2023), 0.03397},      {Date(23, Month::June, 2023), 0.03400},
     {Date(26, Month::June, 2023), 0.03400},      {Date(27, Month::June, 2023), 0.03397},
     {Date(28, Month::June, 2023), 0.03400},      {Date(29, Month::June, 2023), 0.03400},
     {Date(30, Month::June, 2023), 0.03400},      {Date(3, Month::July, 2023), 0.03399},
     {Date(4, Month::July, 2023), 0.03401},       {Date(5, Month::July, 2023), 0.03404},
     {Date(6, Month::July, 2023), 0.03406},       {Date(7, Month::July, 2023), 0.03406},
     {Date(10, Month::July, 2023), 0.03402},      {Date(11, Month::July, 2023), 0.03404},
     {Date(12, Month::July, 2023), 0.03404},      {Date(13, Month::July, 2023), 0.03401},
     {Date(14, Month::July, 2023), 0.03402},      {Date(17, Month::July, 2023), 0.03400},
     {Date(18, Month::July, 2023), 0.03399},      {Date(19, Month::July, 2023), 0.03400},
     {Date(20, Month::July, 2023), 0.03403},      {Date(21, Month::July, 2023), 0.03404},
     {Date(24, Month::July, 2023), 0.03405},      {Date(25, Month::July, 2023), 0.03405},
     {Date(26, Month::July, 2023), 0.03402},      {Date(27, Month::July, 2023), 0.03403},
     {Date(28, Month::July, 2023), 0.03404},      {Date(31, Month::July, 2023), 0.03392},
     {Date(1, Month::August, 2023), 0.03404},     {Date(2, Month::August, 2023), 0.03655},
     {Date(3, Month::August, 2023), 0.03653},     {Date(4, Month::August, 2023), 0.03653},
     {Date(7, Month::August, 2023), 0.03653},     {Date(8, Month::August, 2023), 0.03652},
     {Date(9, Month::August, 2023), 0.03649},     {Date(10, Month::August, 2023), 0.03652},
     {Date(11, Month::August, 2023), 0.03653},    {Date(14, Month::August, 2023), 0.03656},
     {Date(15, Month::August, 2023), 0.03657},    {Date(16, Month::August, 2023), 0.03654},
     {Date(17, Month::August, 2023), 0.03654},    {Date(18, Month::August, 2023), 0.03655},
     {Date(21, Month::August, 2023), 0.03654},    {Date(22, Month::August, 2023), 0.03655},
     {Date(23, Month::August, 2023), 0.03652},    {Date(24, Month::August, 2023), 0.03649},
     {Date(25, Month::August, 2023), 0.03652},    {Date(28, Month::August, 2023), 0.03651},
     {Date(29, Month::August, 2023), 0.03652},    {Date(30, Month::August, 2023), 0.03652},
     {Date(31, Month::August, 2023), 0.03646},    {Date(1, Month::September, 2023), 0.03652},
     {Date(4, Month::September, 2023), 0.03652},  {Date(5, Month::September, 2023), 0.03651},
     {Date(6, Month::September, 2023), 0.03652},  {Date(7, Month::September, 2023), 0.03652},
     {Date(8, Month::September, 2023), 0.03653},  {Date(11, Month::September, 2023), 0.03652},
     {Date(12, Month::September, 2023), 0.03654}, {Date(13, Month::September, 2023), 0.03652},
     {Date(14, Month::September, 2023), 0.03653}, {Date(15, Month::September, 2023), 0.03650},
     {Date(18, Month::September, 2023), 0.03648}, {Date(19, Month::September, 2023), 0.03651},
     {Date(20, Month::September, 2023), 0.03901}, {Date(21, Month::September, 2023), 0.03902},
     {Date(22, Month::September, 2023), 0.03905}, {Date(25, Month::September, 2023), 0.03904},
     {Date(26, Month::September, 2023), 0.03904}, {Date(27, Month::September, 2023), 0.03905},
     {Date(28, Month::September, 2023), 0.03906}, {Date(29, Month::September, 2023), 0.03880},
     {Date(2, Month::October, 2023), 0.03899},    {Date(3, Month::October, 2023), 0.03900},
     {Date(4, Month::October, 2023), 0.03901},    {Date(5, Month::October, 2023), 0.03900},
     {Date(6, Month::October, 2023), 0.03899},    {Date(9, Month::October, 2023), 0.03900},
     {Date(10, Month::October, 2023), 0.03899},   {Date(11, Month::October, 2023), 0.03901},
     {Date(12, Month::October, 2023), 0.03901},   {Date(13, Month::October, 2023), 0.03903},
     {Date(16, Month::October, 2023), 0.03902},   {Date(17, Month::October, 2023), 0.03904},
     {Date(18, Month::October, 2023), 0.03903},   {Date(19, Month::October, 2023), 0.03905},
     {Date(20, Month::October, 2023), 0.03905},   {Date(23, Month::October, 2023), 0.03905},
     {Date(24, Month::October, 2023), 0.03904},   {Date(25, Month::October, 2023), 0.03900},
     {Date(26, Month::October, 2023), 0.03901},   {Date(27, Month::October, 2023), 0.03903},
     {Date(30, Month::October, 2023), 0.03899},   {Date(31, Month::October, 2023), 0.03882},
     {Date(1, Month::November, 2023), 0.03900},   {Date(2, Month::November, 2023), 0.03903},
     {Date(3, Month::November, 2023), 0.03902},   {Date(6, Month::November, 2023), 0.03900},
     {Date(7, Month::November, 2023), 0.03902},   {Date(8, Month::November, 2023), 0.03902},
     {Date(9, Month::November, 2023), 0.03902},   {Date(10, Month::November, 2023), 0.03904},
     {Date(13, Month::November, 2023), 0.03903},  {Date(14, Month::November, 2023), 0.03902},
     {Date(15, Month::November, 2023), 0.03899},  {Date(16, Month::November, 2023), 0.03906},
     {Date(17, Month::November, 2023), 0.03902},  {Date(20, Month::November, 2023), 0.03903},
     {Date(21, Month::November, 2023), 0.03901},  {Date(22, Month::November, 2023), 0.03902},
     {Date(23, Month::November, 2023), 0.03902},  {Date(24, Month::November, 2023), 0.03904},
     {Date(27, Month::November, 2023), 0.03903},  {Date(28, Month::November, 2023), 0.03903},
     {Date(29, Month::November, 2023), 0.03902},  {Date(30, Month::November, 2023), 0.03891},
     {Date(1, Month::December, 2023), 0.03904},   {Date(4, Month::December, 2023), 0.03904},
     {Date(5, Month::December, 2023), 0.03905},   {Date(6, Month::December, 2023), 0.03904},
     {Date(7, Month::December, 2023), 0.03903},   {Date(8, Month::December, 2023), 0.03903},
     {Date(11, Month::December, 2023), 0.03902},  {Date(12, Month::December, 2023), 0.03905},
     {Date(13, Month::December, 2023), 0.03905},  {Date(14, Month::December, 2023), 0.03907},
     {Date(15, Month::December, 2023), 0.03904},  {Date(18, Month::December, 2023), 0.03901},
     {Date(19, Month::December, 2023), 0.03901},  {Date(20, Month::December, 2023), 0.03901},
     {Date(21, Month::December, 2023), 0.03899},  {Date(22, Month::December, 2023), 0.03899},
     {Date(27, Month::December, 2023), 0.03900},  {Date(28, Month::December, 2023), 0.03900},
     {Date(29, Month::December, 2023), 0.03882},  {Date(2, Month::January, 2024), 0.03906},
     {Date(3, Month::January, 2024), 0.03904},    {Date(4, Month::January, 2024), 0.03902},
     {Date(5, Month::January, 2024), 0.03905},    {Date(8, Month::January, 2024), 0.03904},
     {Date(9, Month::January, 2024), 0.03904},    {Date(10, Month::January, 2024), 0.03906},
     {Date(11, Month::January, 2024), 0.03905},   {Date(12, Month::January, 2024), 0.03904},
     {Date(15, Month::January, 2024), 0.03902},   {Date(16, Month::January, 2024), 0.03905},
     {Date(17, Month::January, 2024), 0.03904},   {Date(18, Month::January, 2024), 0.03907},
     {Date(19, Month::January, 2024), 0.03904},   {Date(22, Month::January, 2024), 0.03902},
     {Date(23, Month::January, 2024), 0.03902},   {Date(24, Month::January, 2024), 0.03905},
     {Date(25, Month::January, 2024), 0.03905},   {Date(26, Month::January, 2024), 0.03904},
     {Date(29, Month::January, 2024), 0.03907},   {Date(30, Month::January, 2024), 0.03907},
     {Date(31, Month::January, 2024), 0.03894},   {Date(1, Month::February, 2024), 0.03905},
     {Date(2, Month::February, 2024), 0.03906},   {Date(5, Month::February, 2024), 0.03907},
     {Date(6, Month::February, 2024), 0.03908},   {Date(7, Month::February, 2024), 0.03908},
     {Date(8, Month::February, 2024), 0.03908},   {Date(9, Month::February, 2024), 0.03910},
     {Date(12, Month::February, 2024), 0.03909},  {Date(13, Month::February, 2024), 0.03909},
     {Date(14, Month::February, 2024), 0.03911},  {Date(15, Month::February, 2024), 0.03911},
     {Date(16, Month::February, 2024), 0.03909},  {Date(19, Month::February, 2024), 0.03910},
     {Date(20, Month::February, 2024), 0.03911},  {Date(21, Month::February, 2024), 0.03910},
     {Date(22, Month::February, 2024), 0.03909},  {Date(23, Month::February, 2024), 0.03907},
     {Date(26, Month::February, 2024), 0.03904},  {Date(27, Month::February, 2024), 0.03905},
     {Date(28, Month::February, 2024), 0.03906},  {Date(29, Month::February, 2024), 0.03887},
     {Date(1, Month::March, 2024), 0.03904},      {Date(4, Month::March, 2024), 0.03903},
     {Date(5, Month::March, 2024), 0.03911},      {Date(6, Month::March, 2024), 0.03905},
     {Date(7, Month::March, 2024), 0.03908},      {Date(8, Month::March, 2024), 0.03907},
     {Date(11, Month::March, 2024), 0.03904},     {Date(12, Month::March, 2024), 0.03905},
     {Date(13, Month::March, 2024), 0.03907},     {Date(14, Month::March, 2024), 0.03908},
     {Date(15, Month::March, 2024), 0.03909},     {Date(18, Month::March, 2024), 0.03909},
     {Date(19, Month::March, 2024), 0.03908},     {Date(20, Month::March, 2024), 0.03908},
     {Date(21, Month::March, 2024), 0.03907},     {Date(22, Month::March, 2024), 0.03909},
     {Date(25, Month::March, 2024), 0.03909},     {Date(26, Month::March, 2024), 0.03906},
     {Date(27, Month::March, 2024), 0.03906},     {Date(28, Month::March, 2024), 0.03899},
     {Date(2, Month::April, 2024), 0.03906},      {Date(3, Month::April, 2024), 0.03911},
     {Date(4, Month::April, 2024), 0.03912},      {Date(5, Month::April, 2024), 0.03907},
     {Date(8, Month::April, 2024), 0.03908},      {Date(9, Month::April, 2024), 0.03909},
     {Date(10, Month::April, 2024), 0.03907},     {Date(11, Month::April, 2024), 0.03907},
     {Date(12, Month::April, 2024), 0.03910},     {Date(15, Month::April, 2024), 0.03907},
     {Date(16, Month::April, 2024), 0.03911},     {Date(17, Month::April, 2024), 0.03908},
     {Date(18, Month::April, 2024), 0.03909},     {Date(19, Month::April, 2024), 0.03910},
     {Date(22, Month::April, 2024), 0.03910},     {Date(23, Month::April, 2024), 0.03908},
     {Date(24, Month::April, 2024), 0.03911}};

const map<Period, double> DiscountingCurveDemo::swapRates = {
    {Period(7, TimeUnit::Days), 0.03905250},    {Period(1, TimeUnit::Months), 0.03913000},
    {Period(3, TimeUnit::Months), 0.03810000},  {Period(6, TimeUnit::Months), 0.03693000},
    {Period(9, TimeUnit::Months), 0.03587850},  {Period(1, TimeUnit::Years), 0.03491000},
    {Period(15, TimeUnit::Months), 0.03381725}, {Period(18, TimeUnit::Months), 0.03289550},
    {Period(21, TimeUnit::Months), 0.03213950}, {Period(2, TimeUnit::Years), 0.03152900},
    {Period(3, TimeUnit::Years), 0.02957500},   {Period(4, TimeUnit::Years), 0.02842400},
    {Period(5, TimeUnit::Years), 0.02778000},   {Period(6, TimeUnit::Years), 0.02744500},
    {Period(7, TimeUnit::Years), 0.02731100},   {Period(8, TimeUnit::Years), 0.02730000},
    {Period(9, TimeUnit::Years), 0.02740000},   {Period(10, TimeUnit::Years), 0.02755900},
    {Period(15, TimeUnit::Years), 0.02836150},  {Period(20, TimeUnit::Years), 0.02805000},
    {Period(25, TimeUnit::Years), 0.02717000},  {Period(30, TimeUnit::Years), 0.02630050},
    {Period(40, TimeUnit::Years), 0.02501225},  {Period(50, TimeUnit::Years), 0.02388000},
};

const vector<pair<AbsoluteOrRelativeDate, AbsoluteOrRelativeDate>> DiscountingCurveDemo::calcSwapTenors =
    {{Period(0, TimeUnit::Days), Period(1, TimeUnit::Days)},
     {Period(0, TimeUnit::Days), Period(7, TimeUnit::Days)},
     {Period(0, TimeUnit::Days), Period(14, TimeUnit::Days)},
     {Period(0, TimeUnit::Days), Period(1, TimeUnit::Months)},
     {Period(0, TimeUnit::Days), Period(2, TimeUnit::Months)},
     {Period(0, TimeUnit::Days), Period(3, TimeUnit::Months)},
     {Period(0, TimeUnit::Days), Period(4, TimeUnit::Months)},
     {Period(0, TimeUnit::Days), Period(5, TimeUnit::Months)},
     {Period(0, TimeUnit::Days), Period(6, TimeUnit::Months)},
     {Period(0, TimeUnit::Days), Period(9, TimeUnit::Months)},
     {Period(0, TimeUnit::Days), Period(1, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(15, TimeUnit::Months)},
     {Period(0, TimeUnit::Days), Period(18, TimeUnit::Months)},
     {Period(0, TimeUnit::Days), Period(21, TimeUnit::Months)},
     {Period(0, TimeUnit::Days), Period(2, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(3, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(4, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(5, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(6, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(7, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(8, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(9, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(10, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(11, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(12, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(13, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(14, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(15, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(20, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(25, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(30, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(35, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(40, TimeUnit::Years)},
     {Period(0, TimeUnit::Days), Period(50, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(1, TimeUnit::Months)},
     {Period(1, TimeUnit::Months), Period(3, TimeUnit::Months)},
     {Period(1, TimeUnit::Months), Period(6, TimeUnit::Months)},
     {Period(1, TimeUnit::Months), Period(9, TimeUnit::Months)},
     {Period(1, TimeUnit::Months), Period(1, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(15, TimeUnit::Months)},
     {Period(1, TimeUnit::Months), Period(18, TimeUnit::Months)},
     {Period(1, TimeUnit::Months), Period(21, TimeUnit::Months)},
     {Period(1, TimeUnit::Months), Period(2, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(3, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(4, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(5, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(6, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(7, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(8, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(9, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(10, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(12, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(15, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(20, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(25, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(30, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(35, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(40, TimeUnit::Years)},
     {Period(1, TimeUnit::Months), Period(50, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(1, TimeUnit::Months)},
     {Period(3, TimeUnit::Months), Period(3, TimeUnit::Months)},
     {Period(3, TimeUnit::Months), Period(6, TimeUnit::Months)},
     {Period(3, TimeUnit::Months), Period(9, TimeUnit::Months)},
     {Period(3, TimeUnit::Months), Period(1, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(15, TimeUnit::Months)},
     {Period(3, TimeUnit::Months), Period(18, TimeUnit::Months)},
     {Period(3, TimeUnit::Months), Period(21, TimeUnit::Months)},
     {Period(3, TimeUnit::Months), Period(2, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(3, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(4, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(5, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(6, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(7, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(8, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(9, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(10, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(12, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(15, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(20, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(25, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(30, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(35, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(40, TimeUnit::Years)},
     {Period(3, TimeUnit::Months), Period(50, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(1, TimeUnit::Months)},
     {Period(6, TimeUnit::Months), Period(3, TimeUnit::Months)},
     {Period(6, TimeUnit::Months), Period(6, TimeUnit::Months)},
     {Period(6, TimeUnit::Months), Period(9, TimeUnit::Months)},
     {Period(6, TimeUnit::Months), Period(1, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(15, TimeUnit::Months)},
     {Period(6, TimeUnit::Months), Period(18, TimeUnit::Months)},
     {Period(6, TimeUnit::Months), Period(21, TimeUnit::Months)},
     {Period(6, TimeUnit::Months), Period(2, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(3, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(4, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(5, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(6, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(7, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(8, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(9, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(10, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(12, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(15, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(20, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(25, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(30, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(35, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(40, TimeUnit::Years)},
     {Period(6, TimeUnit::Months), Period(50, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(1, TimeUnit::Months)},
     {Period(9, TimeUnit::Months), Period(3, TimeUnit::Months)},
     {Period(9, TimeUnit::Months), Period(6, TimeUnit::Months)},
     {Period(9, TimeUnit::Months), Period(9, TimeUnit::Months)},
     {Period(9, TimeUnit::Months), Period(1, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(15, TimeUnit::Months)},
     {Period(9, TimeUnit::Months), Period(18, TimeUnit::Months)},
     {Period(9, TimeUnit::Months), Period(21, TimeUnit::Months)},
     {Period(9, TimeUnit::Months), Period(2, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(3, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(4, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(5, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(6, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(7, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(8, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(9, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(10, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(12, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(15, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(20, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(25, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(30, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(35, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(40, TimeUnit::Years)},
     {Period(9, TimeUnit::Months), Period(50, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(1, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(1, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(1, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(1, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(15, TimeUnit::Months)},
     {Period(1, TimeUnit::Years), Period(18, TimeUnit::Months)},
     {Period(1, TimeUnit::Years), Period(21, TimeUnit::Months)},
     {Period(1, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(1, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(1, TimeUnit::Months)},
     {Period(15, TimeUnit::Months), Period(3, TimeUnit::Months)},
     {Period(15, TimeUnit::Months), Period(6, TimeUnit::Months)},
     {Period(15, TimeUnit::Months), Period(9, TimeUnit::Months)},
     {Period(15, TimeUnit::Months), Period(1, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(15, TimeUnit::Months)},
     {Period(15, TimeUnit::Months), Period(18, TimeUnit::Months)},
     {Period(15, TimeUnit::Months), Period(21, TimeUnit::Months)},
     {Period(15, TimeUnit::Months), Period(2, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(3, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(4, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(5, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(6, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(7, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(8, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(9, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(10, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(12, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(15, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(20, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(25, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(30, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(35, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(40, TimeUnit::Years)},
     {Period(15, TimeUnit::Months), Period(50, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(1, TimeUnit::Months)},
     {Period(18, TimeUnit::Months), Period(3, TimeUnit::Months)},
     {Period(18, TimeUnit::Months), Period(6, TimeUnit::Months)},
     {Period(18, TimeUnit::Months), Period(9, TimeUnit::Months)},
     {Period(18, TimeUnit::Months), Period(1, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(15, TimeUnit::Months)},
     {Period(18, TimeUnit::Months), Period(18, TimeUnit::Months)},
     {Period(18, TimeUnit::Months), Period(21, TimeUnit::Months)},
     {Period(18, TimeUnit::Months), Period(2, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(3, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(4, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(5, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(6, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(7, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(8, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(9, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(10, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(12, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(15, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(20, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(25, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(30, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(35, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(40, TimeUnit::Years)},
     {Period(18, TimeUnit::Months), Period(50, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(1, TimeUnit::Months)},
     {Period(21, TimeUnit::Months), Period(3, TimeUnit::Months)},
     {Period(21, TimeUnit::Months), Period(6, TimeUnit::Months)},
     {Period(21, TimeUnit::Months), Period(9, TimeUnit::Months)},
     {Period(21, TimeUnit::Months), Period(1, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(15, TimeUnit::Months)},
     {Period(21, TimeUnit::Months), Period(18, TimeUnit::Months)},
     {Period(21, TimeUnit::Months), Period(21, TimeUnit::Months)},
     {Period(21, TimeUnit::Months), Period(2, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(3, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(4, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(5, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(6, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(7, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(8, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(9, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(10, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(12, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(15, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(20, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(25, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(30, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(35, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(40, TimeUnit::Years)},
     {Period(21, TimeUnit::Months), Period(50, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(2, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(2, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(2, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(2, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(15, TimeUnit::Months)},
     {Period(2, TimeUnit::Years), Period(18, TimeUnit::Months)},
     {Period(2, TimeUnit::Years), Period(21, TimeUnit::Months)},
     {Period(2, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(2, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(3, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(3, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(3, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(3, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(15, TimeUnit::Months)},
     {Period(3, TimeUnit::Years), Period(18, TimeUnit::Months)},
     {Period(3, TimeUnit::Years), Period(21, TimeUnit::Months)},
     {Period(3, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(3, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(4, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(4, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(4, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(4, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(15, TimeUnit::Months)},
     {Period(4, TimeUnit::Years), Period(18, TimeUnit::Months)},
     {Period(4, TimeUnit::Years), Period(21, TimeUnit::Months)},
     {Period(4, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(4, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(5, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(5, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(5, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(5, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(15, TimeUnit::Months)},
     {Period(5, TimeUnit::Years), Period(18, TimeUnit::Months)},
     {Period(5, TimeUnit::Years), Period(21, TimeUnit::Months)},
     {Period(5, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(5, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(6, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(6, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(6, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(6, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(15, TimeUnit::Months)},
     {Period(6, TimeUnit::Years), Period(18, TimeUnit::Months)},
     {Period(6, TimeUnit::Years), Period(21, TimeUnit::Months)},
     {Period(6, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(6, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(7, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(7, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(7, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(7, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(15, TimeUnit::Months)},
     {Period(7, TimeUnit::Years), Period(18, TimeUnit::Months)},
     {Period(7, TimeUnit::Years), Period(21, TimeUnit::Months)},
     {Period(7, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(7, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(8, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(8, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(8, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(8, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(15, TimeUnit::Months)},
     {Period(8, TimeUnit::Years), Period(18, TimeUnit::Months)},
     {Period(8, TimeUnit::Years), Period(21, TimeUnit::Months)},
     {Period(8, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(8, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(9, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(9, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(9, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(9, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(15, TimeUnit::Months)},
     {Period(9, TimeUnit::Years), Period(18, TimeUnit::Months)},
     {Period(9, TimeUnit::Years), Period(21, TimeUnit::Months)},
     {Period(9, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(9, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(10, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(10, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(10, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(10, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(15, TimeUnit::Months)},
     {Period(10, TimeUnit::Years), Period(18, TimeUnit::Months)},
     {Period(10, TimeUnit::Years), Period(21, TimeUnit::Months)},
     {Period(10, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(10, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(12, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(12, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(12, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(12, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(12, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(15, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(15, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(15, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(15, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(15, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(20, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(20, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(20, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(20, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(20, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(25, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(25, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(25, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(25, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(25, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(30, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(30, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(30, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(30, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(30, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(35, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(35, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(35, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(35, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(35, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(40, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(40, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(40, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(40, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(40, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(1, TimeUnit::Months)},
     {Period(50, TimeUnit::Years), Period(3, TimeUnit::Months)},
     {Period(50, TimeUnit::Years), Period(6, TimeUnit::Months)},
     {Period(50, TimeUnit::Years), Period(9, TimeUnit::Months)},
     {Period(50, TimeUnit::Years), Period(1, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(2, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(3, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(4, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(5, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(6, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(7, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(8, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(9, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(10, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(12, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(15, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(20, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(25, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(30, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(35, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(40, TimeUnit::Years)},
     {Period(50, TimeUnit::Years), Period(50, TimeUnit::Years)},
     {Date(8, Month::March, 2023), Date(8, Month::June, 2024)},
     {Date(15, Month::March, 2023), Date(15, Month::March, 2025)},
     {Date(22, Month::March, 2023), Date(22, Month::September, 2024)},
     {Date(23, Month::March, 2023), Date(15, Month::March, 2025)},
     {Date(28, Month::March, 2023), Period(444, TimeUnit::Days)},
     {Date(4, Month::April, 2023), Date(15, Month::August, 2024)},
     {Date(4, Month::April, 2023), Date(15, Month::March, 2025)},
     {Date(5, Month::April, 2023), Period(617, TimeUnit::Days)},
     {Date(17, Month::April, 2023), Date(22, Month::September, 2024)},
     {Date(3, Month::May, 2023), Date(4, Month::October, 2038)},
     {Date(12, Month::June, 2023), Period(640, TimeUnit::Days)},
     {Date(12, Month::June, 2023), Period(3352, TimeUnit::Days)},
     {Date(13, Month::July, 2023), Date(4, Month::October, 2038)},
     {Date(18, Month::July, 2023), Date(4, Month::October, 2052)},
     {Date(1, Month::August, 2023), Date(1, Month::August, 2024)},
     {Date(2, Month::August, 2023), Date(2, Month::May, 2024)},
     {Date(30, Month::August, 2023), Date(17, Month::July, 2024)},
     {Date(19, Month::September, 2023), Date(4, Month::December, 2030)},
     {Date(20, Month::September, 2023), Date(20, Month::September, 2025)},
     {Date(20, Month::September, 2023), Date(20, Month::September, 2033)},
     {Date(26, Month::September, 2023), Date(26, Month::December, 2024)},
     {Date(27, Month::September, 2023), Date(15, Month::May, 2024)},
     {Date(27, Month::September, 2023), Date(21, Month::August, 2024)},
     {Date(28, Month::September, 2023), Date(28, Month::July, 2024)},
     {Date(29, Month::September, 2023), Date(30, Month::June, 2024)},
     {Date(4, Month::October, 2023), Date(17, Month::July, 2024)},
     {Date(17, Month::October, 2023), Date(17, Month::October, 2024)},
     {Date(17, Month::October, 2023), Date(4, Month::April, 2044)},
     {Date(18, Month::October, 2023), Date(18, Month::October, 2024)},
     {Date(20, Month::October, 2023), Date(13, Month::September, 2024)},
     {Date(25, Month::October, 2023), Date(25, Month::September, 2024)},
     {Date(31, Month::October, 2023), Date(15, Month::February, 2025)},
     {Date(31, Month::October, 2023), Date(20, Month::September, 2025)},
     {Date(31, Month::October, 2023), Date(20, Month::December, 2025)},
     {Date(6, Month::November, 2023), Date(6, Month::July, 2024)},
     {Date(7, Month::November, 2023), Date(7, Month::September, 2024)},
     {Date(7, Month::November, 2023), Date(4, Month::April, 2044)},
     {Date(8, Month::November, 2023), Date(8, Month::August, 2024)},
     {Date(8, Month::November, 2023), Date(8, Month::May, 2025)},
     {Date(14, Month::November, 2023), Date(14, Month::May, 2024)},
     {Date(14, Month::November, 2023), Date(4, Month::October, 2038)},
     {Date(15, Month::November, 2023), Date(15, Month::July, 2024)},
     {Date(17, Month::November, 2023), Date(17, Month::July, 2024)},
     {Date(17, Month::November, 2023), Date(12, Month::December, 2024)},
     {Date(20, Month::November, 2023), Date(20, Month::September, 2024)},
     {Date(20, Month::November, 2023), Date(20, Month::November, 2024)},
     {Date(20, Month::November, 2023), Date(12, Month::December, 2024)},
     {Date(21, Month::November, 2023), Date(21, Month::May, 2024)},
     {Date(21, Month::November, 2023), Date(21, Month::August, 2024)},
     {Date(24, Month::November, 2023), Date(24, Month::June, 2024)},
     {Date(29, Month::November, 2023), Date(29, Month::May, 2024)},
     {Date(29, Month::November, 2023), Date(29, Month::June, 2024)},
     {Date(30, Month::November, 2023), Date(31, Month::July, 2024)},
     {Date(30, Month::November, 2023), Date(31, Month::October, 2024)},
     {Date(6, Month::December, 2023), Date(17, Month::May, 2024)},
     {Date(11, Month::December, 2023), Date(11, Month::December, 2024)},
     {Date(16, Month::December, 2023), Date(16, Month::December, 2024)},
     {Date(18, Month::December, 2023), Date(4, Month::October, 2052)},
     {Date(20, Month::December, 2023), Date(20, Month::June, 2024)},
     {Date(20, Month::December, 2023), Date(20, Month::September, 2025)},
     {Date(20, Month::December, 2023), Date(20, Month::December, 2025)},
     {Date(20, Month::December, 2023), Date(20, Month::December, 2032)},
     {Date(21, Month::December, 2023), Date(21, Month::June, 2024)},
     {Date(21, Month::December, 2023), Date(21, Month::September, 2024)},
     {Date(22, Month::December, 2023), Date(22, Month::December, 2024)},
     {Date(3, Month::January, 2024), Date(3, Month::June, 2024)},
     {Date(4, Month::January, 2024), Date(4, Month::January, 2025)},
     {Date(9, Month::January, 2024), Date(9, Month::July, 2024)},
     {Date(9, Month::January, 2024), Date(9, Month::January, 2025)},
     {Date(10, Month::January, 2024), Date(10, Month::July, 2024)},
     {Date(19, Month::January, 2024), Date(19, Month::October, 2024)},
     {Date(19, Month::January, 2024), Date(19, Month::April, 2025)},
     {Date(25, Month::January, 2024), Date(25, Month::January, 2025)},
     {Date(1, Month::February, 2024), Date(1, Month::February, 2025)},
     {Date(6, Month::February, 2024), Date(6, Month::February, 2025)},
     {Date(4, Month::March, 2024), Date(13, Month::March, 2025)},
     {Date(11, Month::March, 2024), Date(12, Month::December, 2025)},
     {Date(20, Month::March, 2024), Date(20, Month::March, 2026)},
     {Date(20, Month::March, 2024), Date(20, Month::March, 2027)},
     {Date(20, Month::March, 2024), Date(20, Month::March, 2029)},
     {Date(20, Month::March, 2024), Date(20, Month::March, 2031)},
     {Date(20, Month::March, 2024), Date(20, Month::March, 2034)},
     {Date(20, Month::March, 2024), Date(20, Month::March, 2036)},
     {Date(20, Month::March, 2024), Date(20, Month::March, 2039)},
     {Date(20, Month::March, 2024), Date(20, Month::March, 2054)},
     {Date(28, Month::March, 2024), Date(31, Month::December, 2024)},
     {Date(8, Month::April, 2024), Date(30, Month::September, 2024)},
     {Date(8, Month::April, 2024), Date(8, Month::April, 2025)},
     {Date(12, Month::April, 2024), Date(30, Month::September, 2024)},
     {Date(17, Month::April, 2024), Date(12, Month::June, 2024)},
     {Date(10, Month::June, 2024), Date(15, Month::February, 2033)},
     {Date(10, Month::June, 2024), Date(15, Month::August, 2048)},
     {Date(19, Month::June, 2024), Period(1, TimeUnit::Days)},
     {Date(19, Month::June, 2024), Period(7, TimeUnit::Days)},
     {Date(19, Month::June, 2024), Period(14, TimeUnit::Days)},
     {Date(19, Month::June, 2024), Period(1, TimeUnit::Months)},
     {Date(19, Month::June, 2024), Period(2, TimeUnit::Months)},
     {Date(19, Month::June, 2024), Period(3, TimeUnit::Months)},
     {Date(19, Month::June, 2024), Period(4, TimeUnit::Months)},
     {Date(19, Month::June, 2024), Period(5, TimeUnit::Months)},
     {Date(19, Month::June, 2024), Period(6, TimeUnit::Months)},
     {Date(19, Month::June, 2024), Period(9, TimeUnit::Months)},
     {Date(19, Month::June, 2024), Period(1, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(15, TimeUnit::Months)},
     {Date(19, Month::June, 2024), Period(18, TimeUnit::Months)},
     {Date(19, Month::June, 2024), Period(21, TimeUnit::Months)},
     {Date(19, Month::June, 2024), Period(2, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(3, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(4, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(5, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(6, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(7, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(8, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(9, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(10, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(11, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(12, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(13, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(14, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(15, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(20, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(25, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(30, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(40, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Period(50, TimeUnit::Years)},
     {Date(19, Month::June, 2024), Date(17, Month::June, 2026)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2026)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2027)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2028)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2029)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2030)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2031)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2032)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2033)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2034)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2036)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2039)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2044)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2049)},
     {Date(19, Month::June, 2024), Date(19, Month::June, 2054)},
     {Date(18, Month::September, 2024), Period(1, TimeUnit::Days)},
     {Date(18, Month::September, 2024), Period(7, TimeUnit::Days)},
     {Date(18, Month::September, 2024), Period(14, TimeUnit::Days)},
     {Date(18, Month::September, 2024), Period(1, TimeUnit::Months)},
     {Date(18, Month::September, 2024), Period(2, TimeUnit::Months)},
     {Date(18, Month::September, 2024), Period(3, TimeUnit::Months)},
     {Date(18, Month::September, 2024), Period(4, TimeUnit::Months)},
     {Date(18, Month::September, 2024), Period(5, TimeUnit::Months)},
     {Date(18, Month::September, 2024), Period(6, TimeUnit::Months)},
     {Date(18, Month::September, 2024), Period(9, TimeUnit::Months)},
     {Date(18, Month::September, 2024), Period(1, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(15, TimeUnit::Months)},
     {Date(18, Month::September, 2024), Period(18, TimeUnit::Months)},
     {Date(18, Month::September, 2024), Period(21, TimeUnit::Months)},
     {Date(18, Month::September, 2024), Period(2, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(3, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(4, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(5, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(6, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(7, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(8, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(9, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(10, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(11, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(12, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(13, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(14, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(15, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(20, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(25, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(30, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(40, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Period(50, TimeUnit::Years)},
     {Date(18, Month::September, 2024), Date(18, Month::December, 2024)},
     {Date(18, Month::September, 2024), Date(18, Month::September, 2025)},
     {Date(18, Month::December, 2024), Period(1, TimeUnit::Days)},
     {Date(18, Month::December, 2024), Period(7, TimeUnit::Days)},
     {Date(18, Month::December, 2024), Period(14, TimeUnit::Days)},
     {Date(18, Month::December, 2024), Period(1, TimeUnit::Months)},
     {Date(18, Month::December, 2024), Period(2, TimeUnit::Months)},
     {Date(18, Month::December, 2024), Period(3, TimeUnit::Months)},
     {Date(18, Month::December, 2024), Period(4, TimeUnit::Months)},
     {Date(18, Month::December, 2024), Period(5, TimeUnit::Months)},
     {Date(18, Month::December, 2024), Period(6, TimeUnit::Months)},
     {Date(18, Month::December, 2024), Period(9, TimeUnit::Months)},
     {Date(18, Month::December, 2024), Period(1, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(15, TimeUnit::Months)},
     {Date(18, Month::December, 2024), Period(18, TimeUnit::Months)},
     {Date(18, Month::December, 2024), Period(21, TimeUnit::Months)},
     {Date(18, Month::December, 2024), Period(2, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(3, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(4, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(5, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(6, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(7, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(8, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(9, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(10, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(11, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(12, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(13, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(14, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(15, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(20, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(25, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(30, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(40, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Period(50, TimeUnit::Years)},
     {Date(18, Month::December, 2024), Date(18, Month::December, 2025)},
     {Date(19, Month::March, 2025), Period(1, TimeUnit::Years)},
     {Date(19, Month::March, 2025), Period(2, TimeUnit::Years)},
     {Date(19, Month::March, 2025), Period(3, TimeUnit::Years)},
     {Date(19, Month::March, 2025), Period(4, TimeUnit::Years)},
     {Date(19, Month::March, 2025), Period(5, TimeUnit::Years)},
     {Date(18, Month::June, 2025), Period(1, TimeUnit::Years)},
     {Date(18, Month::June, 2025), Period(2, TimeUnit::Years)},
     {Date(18, Month::June, 2025), Period(3, TimeUnit::Years)},
     {Date(18, Month::June, 2025), Period(4, TimeUnit::Years)},
     {Date(18, Month::June, 2025), Period(5, TimeUnit::Years)},
     {Date(18, Month::June, 2025), Date(18, Month::June, 2026)},
     {Date(17, Month::September, 2025), Period(1, TimeUnit::Years)},
     {Date(17, Month::September, 2025), Period(2, TimeUnit::Years)},
     {Date(17, Month::September, 2025), Period(3, TimeUnit::Years)},
     {Date(17, Month::September, 2025), Period(4, TimeUnit::Years)},
     {Date(17, Month::September, 2025), Period(5, TimeUnit::Years)},
     {Date(17, Month::September, 2025), Date(17, Month::September, 2026)},
     {Date(17, Month::September, 2025), Date(17, Month::September, 2027)},
     {Date(17, Month::December, 2025), Period(1, TimeUnit::Years)},
     {Date(17, Month::December, 2025), Period(2, TimeUnit::Years)},
     {Date(17, Month::December, 2025), Period(3, TimeUnit::Years)},
     {Date(17, Month::December, 2025), Period(4, TimeUnit::Years)},
     {Date(17, Month::December, 2025), Period(5, TimeUnit::Years)},
     {Date(17, Month::December, 2025), Date(17, Month::December, 2026)},
     {Date(17, Month::December, 2025), Date(17, Month::December, 2027)},
     {Date(18, Month::March, 2026), Period(1, TimeUnit::Years)},
     {Date(18, Month::March, 2026), Period(2, TimeUnit::Years)},
     {Date(18, Month::March, 2026), Period(3, TimeUnit::Years)},
     {Date(18, Month::March, 2026), Period(4, TimeUnit::Years)},
     {Date(18, Month::March, 2026), Period(5, TimeUnit::Years)},
     {Date(17, Month::June, 2026), Period(1, TimeUnit::Years)},
     {Date(17, Month::June, 2026), Period(2, TimeUnit::Years)},
     {Date(17, Month::June, 2026), Period(3, TimeUnit::Years)},
     {Date(17, Month::June, 2026), Period(4, TimeUnit::Years)},
     {Date(17, Month::June, 2026), Period(5, TimeUnit::Years)},
     {Date(17, Month::June, 2026), Date(17, Month::June, 2027)},
     {Date(16, Month::September, 2026), Period(1, TimeUnit::Years)},
     {Date(16, Month::September, 2026), Period(2, TimeUnit::Years)},
     {Date(16, Month::September, 2026), Period(3, TimeUnit::Years)},
     {Date(16, Month::September, 2026), Period(5, TimeUnit::Years)},
     {Date(16, Month::September, 2026), Date(16, Month::September, 2027)},
     {Date(16, Month::September, 2026), Date(16, Month::September, 2028)},
     {Date(16, Month::December, 2026), Period(1, TimeUnit::Years)},
     {Date(16, Month::December, 2026), Period(2, TimeUnit::Years)},
     {Date(16, Month::December, 2026), Period(3, TimeUnit::Years)},
     {Date(16, Month::December, 2026), Period(5, TimeUnit::Years)},
     {Date(16, Month::December, 2026), Date(16, Month::December, 2028)},
     {Date(17, Month::March, 2027), Period(1, TimeUnit::Years)},
     {Date(17, Month::March, 2027), Period(2, TimeUnit::Years)},
     {Date(17, Month::March, 2027), Period(3, TimeUnit::Years)},
     {Date(17, Month::March, 2027), Period(5, TimeUnit::Years)},
     {Date(17, Month::March, 2027), Date(17, Month::March, 2029)},
     {Date(16, Month::June, 2027), Period(1, TimeUnit::Years)},
     {Date(16, Month::June, 2027), Period(2, TimeUnit::Years)},
     {Date(16, Month::June, 2027), Period(3, TimeUnit::Years)},
     {Date(16, Month::June, 2027), Period(5, TimeUnit::Years)},
     {Date(16, Month::June, 2027), Date(16, Month::June, 2028)},
     {Date(16, Month::June, 2027), Date(16, Month::June, 2029)},
     {Date(15, Month::September, 2027), Period(1, TimeUnit::Years)},
     {Date(15, Month::September, 2027), Period(2, TimeUnit::Years)},
     {Date(15, Month::September, 2027), Period(3, TimeUnit::Years)},
     {Date(15, Month::September, 2027), Period(5, TimeUnit::Years)},
     {Date(15, Month::September, 2027), Date(15, Month::September, 2028)},
     {Date(15, Month::December, 2027), Period(1, TimeUnit::Years)},
     {Date(15, Month::December, 2027), Period(2, TimeUnit::Years)},
     {Date(15, Month::December, 2027), Period(3, TimeUnit::Years)},
     {Date(15, Month::December, 2027), Period(5, TimeUnit::Years)},
     {Date(15, Month::March, 2028), Period(1, TimeUnit::Years)},
     {Date(15, Month::March, 2028), Period(2, TimeUnit::Years)},
     {Date(15, Month::March, 2028), Period(3, TimeUnit::Years)},
     {Date(15, Month::March, 2028), Period(5, TimeUnit::Years)},
     {Date(15, Month::March, 2028), Date(15, Month::March, 2029)},
     {Date(21, Month::June, 2028), Period(1, TimeUnit::Years)},
     {Date(21, Month::June, 2028), Period(2, TimeUnit::Years)},
     {Date(21, Month::June, 2028), Period(3, TimeUnit::Years)},
     {Date(21, Month::June, 2028), Period(5, TimeUnit::Years)},
     {Date(21, Month::June, 2028), Date(21, Month::June, 2029)},
     {Date(20, Month::September, 2028), Period(1, TimeUnit::Years)},
     {Date(20, Month::September, 2028), Period(2, TimeUnit::Years)},
     {Date(20, Month::September, 2028), Period(3, TimeUnit::Years)},
     {Date(20, Month::September, 2028), Period(5, TimeUnit::Years)},
     {Date(20, Month::September, 2028), Date(20, Month::September, 2029)},
     {Date(20, Month::September, 2028), Date(20, Month::September, 2030)},
     {Date(20, Month::December, 2028), Period(1, TimeUnit::Years)},
     {Date(20, Month::December, 2028), Period(2, TimeUnit::Years)},
     {Date(20, Month::December, 2028), Period(3, TimeUnit::Years)},
     {Date(20, Month::December, 2028), Period(5, TimeUnit::Years)},
     {Date(20, Month::December, 2028), Date(20, Month::December, 2030)},
     {Date(20, Month::December, 2028), Date(20, Month::December, 2033)},
     {Date(21, Month::March, 2029), Period(1, TimeUnit::Years)},
     {Date(21, Month::March, 2029), Period(2, TimeUnit::Years)},
     {Date(21, Month::March, 2029), Period(3, TimeUnit::Years)},
     {Date(21, Month::March, 2029), Period(5, TimeUnit::Years)},
     {Date(21, Month::March, 2029), Date(21, Month::March, 2030)},
     {Date(21, Month::March, 2029), Date(21, Month::March, 2031)},
     {Date(20, Month::June, 2029), Period(1, TimeUnit::Years)},
     {Date(20, Month::June, 2029), Period(2, TimeUnit::Years)},
     {Date(20, Month::June, 2029), Period(3, TimeUnit::Years)},
     {Date(20, Month::June, 2029), Period(5, TimeUnit::Years)},
     {Date(20, Month::June, 2029), Date(20, Month::June, 2030)},
     {Date(20, Month::June, 2029), Date(20, Month::June, 2031)},
     {Date(19, Month::September, 2029), Period(1, TimeUnit::Years)},
     {Date(19, Month::September, 2029), Period(2, TimeUnit::Years)},
     {Date(19, Month::September, 2029), Period(3, TimeUnit::Years)},
     {Date(19, Month::September, 2029), Period(5, TimeUnit::Years)},
     {Date(19, Month::September, 2029), Date(19, Month::September, 2031)},
     {Date(19, Month::December, 2029), Period(1, TimeUnit::Years)},
     {Date(19, Month::December, 2029), Period(2, TimeUnit::Years)},
     {Date(19, Month::December, 2029), Period(3, TimeUnit::Years)},
     {Date(19, Month::December, 2029), Period(5, TimeUnit::Years)},
     {Date(19, Month::December, 2029), Date(19, Month::December, 2031)},
     {Date(20, Month::March, 2030), Period(1, TimeUnit::Years)},
     {Date(20, Month::March, 2030), Period(2, TimeUnit::Years)},
     {Date(20, Month::March, 2030), Period(3, TimeUnit::Years)},
     {Date(20, Month::March, 2030), Period(5, TimeUnit::Years)},
     {Date(19, Month::June, 2030), Period(1, TimeUnit::Years)},
     {Date(19, Month::June, 2030), Period(2, TimeUnit::Years)},
     {Date(19, Month::June, 2030), Period(3, TimeUnit::Years)},
     {Date(19, Month::June, 2030), Period(5, TimeUnit::Years)},
     {Date(18, Month::September, 2030), Period(1, TimeUnit::Years)},
     {Date(18, Month::September, 2030), Period(2, TimeUnit::Years)},
     {Date(18, Month::September, 2030), Period(3, TimeUnit::Years)},
     {Date(18, Month::September, 2030), Period(5, TimeUnit::Years)},
     {Date(18, Month::September, 2030), Date(18, Month::September, 2033)},
     {Date(16, Month::December, 2030), Date(16, Month::December, 2035)},
     {Date(18, Month::December, 2030), Period(1, TimeUnit::Years)},
     {Date(18, Month::December, 2030), Period(2, TimeUnit::Years)},
     {Date(18, Month::December, 2030), Period(3, TimeUnit::Years)},
     {Date(18, Month::December, 2030), Period(5, TimeUnit::Years)},
     {Date(18, Month::December, 2030), Date(18, Month::December, 2033)},
     {Date(19, Month::March, 2031), Period(1, TimeUnit::Years)},
     {Date(19, Month::March, 2031), Period(2, TimeUnit::Years)},
     {Date(19, Month::March, 2031), Period(3, TimeUnit::Years)},
     {Date(19, Month::March, 2031), Period(5, TimeUnit::Years)},
     {Date(19, Month::March, 2031), Date(19, Month::March, 2034)},
     {Date(18, Month::June, 2031), Period(1, TimeUnit::Years)},
     {Date(18, Month::June, 2031), Period(2, TimeUnit::Years)},
     {Date(18, Month::June, 2031), Period(3, TimeUnit::Years)},
     {Date(18, Month::June, 2031), Period(5, TimeUnit::Years)},
     {Date(17, Month::September, 2031), Period(1, TimeUnit::Years)},
     {Date(17, Month::September, 2031), Period(2, TimeUnit::Years)},
     {Date(17, Month::September, 2031), Period(3, TimeUnit::Years)},
     {Date(17, Month::September, 2031), Period(5, TimeUnit::Years)},
     {Date(17, Month::September, 2031), Date(17, Month::September, 2033)},
     {Date(17, Month::December, 2031), Period(1, TimeUnit::Years)},
     {Date(17, Month::December, 2031), Period(2, TimeUnit::Years)},
     {Date(17, Month::December, 2031), Period(3, TimeUnit::Years)},
     {Date(17, Month::December, 2031), Period(5, TimeUnit::Years)},
     {Date(17, Month::December, 2031), Date(17, Month::December, 2033)},
     {Date(17, Month::March, 2032), Period(1, TimeUnit::Years)},
     {Date(17, Month::March, 2032), Period(2, TimeUnit::Years)},
     {Date(17, Month::March, 2032), Period(3, TimeUnit::Years)},
     {Date(17, Month::March, 2032), Period(5, TimeUnit::Years)},
     {Date(17, Month::March, 2032), Date(17, Month::March, 2034)},
     {Date(16, Month::June, 2032), Period(1, TimeUnit::Years)},
     {Date(16, Month::June, 2032), Period(2, TimeUnit::Years)},
     {Date(16, Month::June, 2032), Period(3, TimeUnit::Years)},
     {Date(16, Month::June, 2032), Period(5, TimeUnit::Years)},
     {Date(15, Month::September, 2032), Period(1, TimeUnit::Years)},
     {Date(15, Month::September, 2032), Period(2, TimeUnit::Years)},
     {Date(15, Month::September, 2032), Period(3, TimeUnit::Years)},
     {Date(15, Month::September, 2032), Period(5, TimeUnit::Years)},
     {Date(15, Month::December, 2032), Period(1, TimeUnit::Years)},
     {Date(15, Month::December, 2032), Period(2, TimeUnit::Years)},
     {Date(15, Month::December, 2032), Period(3, TimeUnit::Years)},
     {Date(15, Month::December, 2032), Period(5, TimeUnit::Years)},
     {Date(16, Month::March, 2033), Period(1, TimeUnit::Years)},
     {Date(16, Month::March, 2033), Period(2, TimeUnit::Years)},
     {Date(16, Month::March, 2033), Period(3, TimeUnit::Years)},
     {Date(16, Month::March, 2033), Period(5, TimeUnit::Years)},
     {Date(15, Month::June, 2033), Period(1, TimeUnit::Years)},
     {Date(15, Month::June, 2033), Period(2, TimeUnit::Years)},
     {Date(15, Month::June, 2033), Period(3, TimeUnit::Years)},
     {Date(15, Month::June, 2033), Period(5, TimeUnit::Years)},
     {Date(15, Month::June, 2033), Date(15, Month::June, 2035)},
     {Date(21, Month::September, 2033), Period(1, TimeUnit::Years)},
     {Date(21, Month::September, 2033), Period(2, TimeUnit::Years)},
     {Date(21, Month::September, 2033), Period(3, TimeUnit::Years)},
     {Date(21, Month::September, 2033), Period(5, TimeUnit::Years)},
     {Date(21, Month::September, 2033), Date(21, Month::September, 2035)},
     {Date(21, Month::September, 2033), Date(21, Month::September, 2038)},
     {Date(21, Month::December, 2033), Period(1, TimeUnit::Years)},
     {Date(21, Month::December, 2033), Period(2, TimeUnit::Years)},
     {Date(21, Month::December, 2033), Period(3, TimeUnit::Years)},
     {Date(21, Month::December, 2033), Period(5, TimeUnit::Years)},
     {Date(21, Month::December, 2033), Date(21, Month::December, 2035)},
     {Date(21, Month::December, 2033), Date(21, Month::December, 2038)},
     {Date(15, Month::March, 2034), Period(1, TimeUnit::Years)},
     {Date(15, Month::March, 2034), Period(2, TimeUnit::Years)},
     {Date(15, Month::March, 2034), Period(3, TimeUnit::Years)},
     {Date(15, Month::March, 2034), Period(5, TimeUnit::Years)},
     {Date(15, Month::March, 2034), Date(15, Month::March, 2036)},
     {Date(21, Month::June, 2034), Period(1, TimeUnit::Years)},
     {Date(21, Month::June, 2034), Period(2, TimeUnit::Years)},
     {Date(21, Month::June, 2034), Period(3, TimeUnit::Years)},
     {Date(21, Month::June, 2034), Period(5, TimeUnit::Years)},
     {Date(21, Month::June, 2034), Period(10, TimeUnit::Years)},
     {Date(20, Month::September, 2034), Period(1, TimeUnit::Years)},
     {Date(20, Month::September, 2034), Period(2, TimeUnit::Years)},
     {Date(20, Month::September, 2034), Period(3, TimeUnit::Years)},
     {Date(20, Month::September, 2034), Period(5, TimeUnit::Years)},
     {Date(20, Month::September, 2034), Period(10, TimeUnit::Years)},
     {Date(20, Month::June, 2035), Period(2, TimeUnit::Years)},
     {Date(20, Month::June, 2035), Date(20, Month::June, 2037)},
     {Date(19, Month::September, 2035), Period(2, TimeUnit::Years)},
     {Date(19, Month::December, 2035), Date(19, Month::December, 2037)},
     {Date(19, Month::March, 2036), Date(19, Month::March, 2038)},
     {Date(18, Month::June, 2036), Period(2, TimeUnit::Years)},
     {Date(17, Month::September, 2036), Period(2, TimeUnit::Years)},
     {Date(17, Month::June, 2037), Period(2, TimeUnit::Years)},
     {Date(16, Month::September, 2037), Period(2, TimeUnit::Years)},
     {Date(16, Month::June, 2038), Period(2, TimeUnit::Years)},
     {Date(15, Month::September, 2038), Period(2, TimeUnit::Years)},
     {Date(15, Month::September, 2038), Date(15, Month::September, 2043)},
     {Date(15, Month::December, 2038), Date(15, Month::December, 2043)},
     {Date(15, Month::June, 2039), Period(2, TimeUnit::Years)},
     {Date(15, Month::June, 2039), Period(5, TimeUnit::Years)},
     {Date(21, Month::September, 2039), Period(2, TimeUnit::Years)},
     {Date(21, Month::September, 2039), Period(5, TimeUnit::Years)},
     {Date(20, Month::June, 2040), Period(2, TimeUnit::Years)},
     {Date(19, Month::September, 2040), Period(2, TimeUnit::Years)},
     {Date(19, Month::June, 2041), Period(2, TimeUnit::Years)},
     {Date(18, Month::September, 2041), Period(2, TimeUnit::Years)},
     {Date(18, Month::June, 2042), Period(2, TimeUnit::Years)},
     {Date(17, Month::September, 2042), Period(2, TimeUnit::Years)},
     {Date(17, Month::June, 2043), Period(2, TimeUnit::Years)},
     {Date(16, Month::September, 2043), Period(2, TimeUnit::Years)},
     {Date(16, Month::September, 2043), Date(16, Month::September, 2048)},
     {Date(15, Month::June, 2044), Period(2, TimeUnit::Years)},
     {Date(15, Month::June, 2044), Period(5, TimeUnit::Years)},
     {Date(15, Month::June, 2044), Period(10, TimeUnit::Years)},
     {Date(21, Month::September, 2044), Period(2, TimeUnit::Years)},
     {Date(21, Month::September, 2044), Period(5, TimeUnit::Years)},
     {Date(21, Month::September, 2044), Period(10, TimeUnit::Years)},
     {Date(16, Month::June, 2049), Period(5, TimeUnit::Years)},
     {Date(15, Month::September, 2049), Period(5, TimeUnit::Years)},
     {Date(17, Month::June, 2054), Period(5, TimeUnit::Years)},
     {Date(17, Month::June, 2054), Period(10, TimeUnit::Years)},
     {Date(16, Month::September, 2054), Period(5, TimeUnit::Years)},
     {Date(16, Month::September, 2054), Period(10, TimeUnit::Years)},
     {Date(18, Month::June, 2059), Period(5, TimeUnit::Years)},
     {Date(17, Month::September, 2059), Period(5, TimeUnit::Years)},
     {Date(18, Month::June, 2064), Period(5, TimeUnit::Years)},
     {Date(18, Month::June, 2064), Period(10, TimeUnit::Years)},
     {Date(17, Month::September, 2064), Period(5, TimeUnit::Years)},
     {Date(17, Month::September, 2064), Period(10, TimeUnit::Years)},
     {Date(19, Month::June, 2069), Period(5, TimeUnit::Years)},
     {Date(18, Month::September, 2069), Period(5, TimeUnit::Years)}};

#ifndef BOOST_TEST_MODULE

int main(int argc, char** argv) {
  DiscountingCurveDemo::main();
  return 0;
}

#endif
